version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    target-branch: "develop"
    schedule:
      interval: "daily"
