line-length = 127
indent-width = 4
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "PT",
    "EM",
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "D203", "D212", "COM812", "Q000", "Q003", "ISC001", "TCH002", "TCH003", "TRY003",
]

[format]
quote-style = "single"
